// Create a new user
POST http://localhost:5000/users
content-type: application/json

{
    "name": "Ogi Admin",
    "email": "admin@gmail.com",
    "password": "12345",
    "confPassword": "12345",
    "role": "Admin"
}


###
// Get all users
GET http://localhost:5000/users


###
// Get Single User
GET http://localhost:5000/users/0c0666ff-6f93-458c-937e-e8dd6410fdbc


###
// Update a user
PATCH  http://localhost:5000/users/0c0666ff-6f93-458c-937e-e8dd6410fdbc
content-type: application/json

{
    "name": "John upd",
    "password": "",
    "confPassword": "",
    "role": "Admin"
}

###
// Delete a user
DELETE http://localhost:5000/users/bf3b1f11-fc79-4ca9-be61-24bde0f6d244


###
// Login User
POST http://localhost:5000/login
content-type: application/json

{
    "email": "admin@gmail.com",
    "password": "12345"
}

###
POST http://localhost:5000/login
content-type: application/json

{
    "email": "user@gmail.com",
    "password": "12345"
}

###
// Get current logged in user
GET http://localhost:5000/me

###
// Logout User
DELETE http://localhost:5000/logout


###
// Get all products
GET http://localhost:5000/products


###
// Get single products
GET http://localhost:5000/products/610f4a47-db81-407c-89d7-71b86191c2aa


###
//Post a new product
POST http://localhost:5000/products
content-type: application/json

{
  "name": "Laptop Baru",
  "merek": "HP",
  "serialNumber": "SN12345"
}

###
// Update a product
PATCH http://localhost:5000/products/610f4a47-db81-407c-89d7-71b86191c2aa
content-type: application/json

{
  "name": "Laptop Baru 2",
  "merek": "HP",
  "serialNumber": "SN12345"
}

###
// Delete a product 
DELETE http://localhost:5000/products/610f4a47-db81-407c-89d7-71b86191c2aa